version: '3.3'

services:
  bot:
    build: .
    environment:
      - DEBUG=false
      - FILE_SECRETS=/run/secrets/secrets
    secrets:
      - secrets
    restart: always

secrets:
  secrets:
    file: ./secrets.yaml